// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://huqunakptjscbjizhcml.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh1cXVuYWtwdGpzY2JqaXpoY21sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzMjQzMzQsImV4cCI6MjA2MzkwMDMzNH0.Prrp9W0K-nLw8hWa6dudHHbFfXb3AZyvB08bQ97Q12k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);